import React from "react";
import { useRouter } from "next/router";
//import VehicleListing from "~/components/VehicleListing";
import { api } from "~/utils/api";
import Head from "next/head";
//import VehicleListing from "~/components/VehicleListing";

/*interface Vehicle {
  id: string;
  year: number;
  make: string;
  model: string;
  miles: number;
  price: number;
  description: string;
}
*/
function Listing() {
  const router = useRouter();
  const { vehicleId } = router.query;
  console.log(vehicleId);

  const vehicle = api.example.getVehicle.useQuery(
    { id: vehicleId as string },
    { enabled: vehicleId !== undefined }
  );

  const { year, make, model } = vehicle.data ?? {};

  return (
    <div className="m-auto mt-11 flex max-w-5xl gap-5">
      <Head>
        <title>Car Auctions</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <h3>
        {year} {make} {model}
      </h3>
    </div>
  );
}

export default Listing;
