import Head from "next/head";
import { useRouter } from "next/router";

function Confirmation() {
  const router = useRouter();
  const { year, make, model, miles, description } = router.query;

  return (
    <div className="{styles.container}">
      <Head>
        <title>Confirmation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2>
          Thank you! Your {year} {make} {model} with {miles} miles on it has
          been submitted!
        </h2>
        <p>{description}</p>
      </main>
    </div>
  );
}

export default Confirmation;
