/*

import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">First Steps →</h3>
              <div className="text-lg">
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Documentation →</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl text-white">
              {hello.data ? hello.data.greeting : "Loading tRPC query..."}
            </p>
            <AuthShowcase />
          </div>
        </div>
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}


*/

import Head from "next/head";
//import Link from "next/link";
import Image from "next/image";
import { api } from "~/utils/api";
import VehicleListing from "~/components/VehicleListing";

/**
 * This is a home page.
 * @returns {JSX.Element}: The JSX Code for Home Page.
 */

export default function Home(): JSX.Element {
  const vehicles = api.example.getVehicles.useQuery();
  console.log(vehicles.data);
  return (
    <div className="m-auto mt-11 flex max-w-5xl gap-5">
      <Head>
        <title>Car Auctions</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>

      <main className="w-full px-2 md:w-4/5 md:pr-0 lg:w-10/12 lg:pl-0">
        <h2 className="pt-5 text-lg font-semibold">Featured Auctions</h2>
        <div>
          {vehicles.data ? (
            <ul className="flex flex-col gap-5 py-5">
              {vehicles.data.map((vehicle) => (
                <li className="" key={vehicle.id}>
                  <VehicleListing vehicle={vehicle} />
                </li>
              ))}
            </ul>
          ) : (
            <p>No cars found.</p>
          )}
        </div>
      </main>
      <aside className="hidden md:block md:w-1/5 md:pr-2 lg:w-2/12 lg:pr-0">
        <h2 className="pt-5 text-lg font-semibold">Current Auctions</h2>
        <div className="current_auctions">
          {vehicles.data ? (
            <ul className="flex flex-wrap gap-5 py-5">
              {vehicles.data.map((vehicle) => (
                <li className="w-full" key={vehicle.id}>
                  <div className="border border-gray-300">
                    <Image
                      src="/images/default-car-image.png"
                      alt="Car Image"
                      width={300}
                      height={200}
                    />
                  </div>
                </li>
              ))}
            </ul>
          ) : (
            <p>No cars found.</p>
          )}
        </div>
      </aside>
    </div>
  );
}

/*

p {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: pre-wrap;
  word-wrap: break-word;
}






interface Vehicle {
  id: string;
  year: string;
  make: string;
  model: string;
  miles: string;
  description: string;
  
  price: number;
  image: string;
}

export async function getServerSideProps(): Promise<{ props: { vehicles: Vehicle[] } }> {
  const prisma = new PrismaClient();
  const vehicles: Vehicle[] = await prisma.vehicle.findMany();
  vehicles.reverse();
  return { props: { vehicles } };
}
*/
