import type { FormEvent } from "react";
import Head from "next/head";
import { useSession } from "next-auth/react";

interface FormElements extends HTMLFormControlsCollection {
  make: HTMLInputElement;
  model: HTMLInputElement;
  year: HTMLInputElement;
  miles: HTMLInputElement;
  price: HTMLInputElement;
  description: HTMLTextAreaElement;
}

interface Form extends HTMLFormElement {
  readonly elements: FormElements;
}

function validateForm(e: FormEvent<Form>): void {
  const make: string = e.currentTarget.elements.make.value;
  const model: string = e.currentTarget.elements.model.value;
  const description: string = e.currentTarget.elements.description.value;

  const year: number = parseInt(e.currentTarget.elements.year.value);
  const miles: number = parseInt(e.currentTarget.elements.miles.value);
  const price: number = parseInt(e.currentTarget.elements.price.value);

  if (
    make === "" ||
    model === "" ||
    year === null ||
    miles === null ||
    price === null ||
    description === ""
  ) {
    alert("Enter missing info!");
    e.preventDefault();
  }
}

function SubmitVehicle() {
  const { data: session, status } = useSession({
    required: true,
  });

  if (session) {
    console.log(session);
  }

  if (status === "loading") {
    return <div>Loading...</div>;
  }

  return (
    <div className=".container m-auto mt-12 flex max-w-5xl flex-col px-2">
      <Head>
        <title>Car Auctions</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col flex-nowrap md:w-3/4">
        <h2 className="pb-4 pt-8">Enter your vehicle information</h2>
        <form
          className="flex flex-col flex-nowrap"
          name="submit"
          action="/api/new-listing"
          onSubmit={(e) => validateForm(e as FormEvent<Form>)}
          method="POST"
        >
          <label className="w-52 pb-3" htmlFor="make">
            Make
          </label>
          <input
            className="mb-5 h-8 w-52 rounded border"
            type="text"
            id="make"
            name="make"
          />

          <label className="w-52 pb-3" htmlFor="model">
            Model
          </label>
          <input
            className="mb-5 h-8 w-52 rounded border"
            type="text"
            id="model"
            name="model"
          />

          <label className="w-52 pb-3" htmlFor="year">
            Year
          </label>
          <input
            className="mb-5 h-8 w-52 rounded border"
            type="number"
            id="year"
            name="year"
          />

          <label className="w-52 pb-3" htmlFor="miles">
            Miles
          </label>
          <input
            className="mb-5 h-8 w-52 rounded border"
            type="number"
            id="miles"
            name="miles"
          />

          <label className="w-52 pb-3" htmlFor="price">
            Price
          </label>
          <input
            className="mb-5 h-8 w-52 rounded border"
            type="number"
            id="price"
            name="price"
          />

          <label className="w-52 pb-3" htmlFor="description">
            Description
          </label>
          <textarea
            className="mb-5 h-32 w-full resize-none rounded border md:w-96"
            id="description"
            name="description"
          />

          <label className="pb-3" htmlFor="images">
            Drag images below or{" "}
            <button id="btn_browse" disabled>
              BROWSE
            </button>
          </label>
          <textarea
            className="mb-5 h-32 w-full resize-none rounded border border-dashed md:w-96"
            id="images"
            name="images"
            disabled
          />

          <button type="submit">SUBMIT</button>
        </form>
      </main>
      <aside>
        <h2 className="pb-4 pt-8">Recently Sold</h2>
        <div className="recently-sold"></div>
      </aside>
    </div>
  );
}

export default SubmitVehicle;
